### ISSUE TITLE
Application continuously updated  (3 times per seconde)

### ISSUE THREAD

**Issue by mick1627** [argoproj/applicationset#322]
After the creation on an ApplicationSet, the applicationset-controller update the application continuously (about 2 times per secondes)

It should wait 3 minutes between 2 updates.

` 

It's running on Kubernetes version  v1.20.9-gke.300
Here the ApplicationSet created :

```yml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-test
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://gitlab.richemont.com/scm_project/ric/ics_cloudplatform/argocd-applicationset/applicationset.git
      revision: HEAD
      files:
      - path: "apps/**/config.json"
  template:
    metadata:
      name: '{{app.name}}-guestbook'
    spec:
      project: test # project is restricted
      source:
        repoURL: '{{app.source}}'
        targetRevision: '{{app.revision}}'
        path: '{{app.path}}'
        helm:
          parameters:
          values:
      destination:
        name: TEST_anthos-cloudplatform-test-1_IAM_admin # cluster is restricted
        namespace: test # namespace is restricted
```
