### ISSUE TITLE
[Proposal]: Git Branch generator

### ISSUE THREAD

**Issue by Segflow** [argoproj/applicationset#358]
We recently started to use Argo CD as a deployment tool. After checking the application set, we believe it's a nice addition to have "Git Branch" generator. 

I can work on the implementation myself, and I believe this will be a nice good first contribution. This issue is more to discuss the spec and the behavior (as well as how we should name things).

Similar to file and directory generator, we propose to have branch generator, could looks something like this:

```yaml
  generators:
  - git:
      repoURL: git@github.com:something/something.git
      revision: "HEAD"
      branches:
      - dev-*
      - feat/*
```

This generator should yield a param for each branch that matches the glob.

For example, if the repository contains these branches:
- main
- dev-test1
- dev-tes2
- feat/new_feature

For each branch that matches the glob, the generator should yield these parameters:
- `branch.fullname`:  The full branch name, e.g *dev-test1* and *feat/new_feature*
- `glob` (help with better name): The piece that matches the asterisk, e.g *test1* and *new_feature* 

The generator should yield:
```json
{"branch.fullname": "dev-test1", "glob": "test1"}
```
```json
{"branch.fullname": "dev-test2", "glob": "test2"}
```
```json
{"branch.fullname": "feat/new_feature", "glob": "new_feature"}
```

# Sanitize branch name

We can also do something similar to cluster generator https://github.com/argoproj-labs/applicationset/pull/237 and just sanitize the branch name and yield it (along with the original name)

```json
{"branch.fullname": "feat/new_feature", "branch.sanitizedName": "feat-new-feature"}
```

# Use case:

This allows developer to create a new Argo CD application by creating a new branch. 

# Full example

```yaml
apiVersion: argoproj.io/v1alpha2 # Notice the v1alpha2 ;)
kind: ApplicationSet
metadata:
  name: dev-envs
spec:
  generators:
  - git:
      repoURL: git@github.com:something/something.git
      revision: "HEAD"   # Not really needed for this generator, but it's a required field.
      branches:
      - deploy/product/dev-*
  template:
    metadata:
      name: '{{glob}}'  # We use `glob` instead of `branch.fullname` as the fullname can contain invalid characters
    spec:
      project: myproject
      source:
        repoURL: git@github.com:something/something.git
        targetRevision: '{{branch.fullname}}'
        path: 'charts/product'
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: 'product-{{glob}}'
```

I would appreciate any feedback on this. I already have a working example as a POC, getting your feedback on the parameter names, what else we can yield is appreciated.
