### ISSUE TITLE
Fan-out generator (create generators based on list of input parameters)

### ISSUE THREAD

**Issue by Roshick** [argoproj/applicationset#376]
My current setup consists of nested directories and I'm running in a lot of issues with ApplicationSets (maybe my architecture is just strange, feel free to give me input for other solutions!).

My directory structure looks like this: /projects/{project}/namespaces/{namespace}/applications/{application}.yaml
with /projects/{project}/clusters/{cluster}.yaml. Now I would like to have a single ApplicationSet that creates an Application for each cluster.yaml+application.yaml pair in each project without having to change the generator each time another project or cluster is added.
Now I'm running into the following problem:
There appears to be no way to "iterate" over each project directory and create the cluster.yaml+application.yaml pairs (e.g. a top level git directory generator based on the project directories that feeds its output to other generators, which create the pairs for each project)

My proposal for a solution to this problem would be a FanOutGenerator which takes two generators: an input generator that creates a list of values and an output generator of which an instance for each value created by the input generator is created. This would allow me to fan out for each project, create the pairs and collect them to create the wished Applications.

If you have any better solutions, let me know! I love this project and would really like to use it for our use case. :)

**Comment by Roshick** [comment]
An example of how I would think it could look like:

```
generators:
  - fan:
      in:
        git:
          repoUrl: someUrl
          revision: HEAD
          directories:
            - path: projects
      out:
        matrix:
          generators:
            - git:
                repoUrl: someUrl
                revision: HEAD
                files:
                  - path: projects/{{path.basename}}/clusters/*
            - git:
                repoUrl: someUrl
                revision: HEAD
                files:
                  - path: projects/{{path.basename}}/applications/*  
```
