### ISSUE TITLE
set global variable in application spec

### ISSUE THREAD

**Issue by alekberovvusal** [argoproj/applicationset#457]
my current applicationset example:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appName
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - list:
          elements:
          - cluster: dev
            url: https://kubernetes.default.svc
          - cluster: prod
            url: https://kubernetes.default.svc
      - git:
          repoURL: https://myUrl/gitops/appName.git
          revision: master
          directories:
          - path: overlays/{{cluster}}/*
  template:
    metadata:
      name: 'myProjectPrefix-{{path.basename}}-{{cluster}}'
    spec:
      project: default
      source:
        repoURL: https://myGitUrl/gitops/appName.git
        targetRevision: master
        path: '{{path}}'
      destination:
        server: '{{url}}'
        namespace: appName-{{cluster}}
      syncPolicy:
        automated:
          prune: true
```

Is there any way to set global variables on top and use those variables in template section. Desired format:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appName
  namespace: argocd
spec:
  generators:
  - vars:
     - gitUrl: 'https://myGitUrl'
     - url: https://kubernetes.default.svc
     - projectName: 'appName'
     - prefix: 'myProjectPrefix'
     
  - matrix:
      generators:
      - list:
          elements:
          - cluster: dev
          - cluster: prod
      - git:
          repoURL: '{{vars.gitUrl}}/gitops/{{vars.projectName}}.git'
          revision: master
          directories:
          - path: overlays/{{cluster}}/*
  template:
    metadata:
      name: '{{vars.prefix}}-{{path.basename}}-{{cluster}}'
    spec:
      project: default
      source:
        repoURL: '{{vars.myGitUrl}}/gitops/{{vars.projectName}}.git'
        targetRevision: master
        path: '{{path}}'
      destination:
        server: '{{url}}'
        namespace: {{vars.projectName}}-{{cluster}}
      syncPolicy:
        automated:
          prune: true
```

As you might notice, second one has more dynamic template structure. Simply by changing some global vars, we can implement this yaml for other applications which is in the same structure. Of course there is no hard pain in finding and replacing these variables one by one but, I think this is a bit clean approach. Please let me know if there is any feature already

**Comment by crenshaw-dev** [comment]
I think you could accomplish this by adding an outer matrix generator whose first generator is a list with a single element containing all your variables.

**Comment by mheiges** [comment]
maybe I misunderstand "adding an outer matrix generator", but this is not allowed

```
kind: ApplicationSet
...
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - service: example
          - clusters:
              selector:
                matchLabels:
                  environment: A
          - clusters:
              selector:
                matchLabels:
                  environment: B
...
  template:
    metadata:
      name: {{ service }}
```


It throws the error `found more than two generators, Matrix support only two`

It does work (`service` acts a global var) with a single cluster though.
