### ISSUE TITLE
How to override a parameter for a matching application?

### ISSUE THREAD

**Issue by gajus** [argoproj/applicationset#465]
I have a basic `ApplicationSet`:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: contra-mother
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@github.com:contra/contra-cluster.git
        revision: development
        directories:
          - path: apps/*
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: git@github.com:contra/contra-cluster.git
        targetRevision: development
        path: "{{path}}"
        helm:
          valueFiles:
            - values.yaml
            - values-development.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: contra
```

However, one of the applications needs to be deployed to a different namespace than "contra".

How do I do that?
