### ISSUE TITLE
SCM Provider with Pull Requests

### ISSUE THREAD

**Issue by fardin01** [argoproj/applicationset#466]
### Problem

Both the SCM Provider generator and Pull Request generator are very good tools for different and valid use cases, but the limitation is that they cannot be used together in a Matrix generator:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp
spec:
  generators:
    - matrix:
        generators:
        - scmProvider:
            github:
              organization: myorg
        - pullRequest:
            github:
              owner: myorg
              repo: < Cannot do this here! >
  template:
   ....
```

We are trying to adopt/migrate to ArgoCD and this is sort of a major blocker. Our testing ecosystem depends on engineers being able to deploy PRs to validate features. According to Pull Request generator docs, "this [the genrator] fits well with the style of building a test environment when you create a pull request". However, when using ApplicationSets, we cannot really have one ApplicationSet with SCM generator and one with Pull Request generator. 

### Proposed solution
Add an extra attribute to SCM generator:
```spec:
  generators:
  - scmProvider:
      github:
        organization: myorg
        allBranches: false
        allPullRequests: true
```
Similar to `allBranches`, `allPullRequests` would create a new ArgoCD app for the open PRs, and could also have a `PRMatch` filter.

So it would be like embedding the Pull Request generator into the SCM generator.

Any feedback/comments would be appreciated.

**Comment by fardin01** [comment]
A better alternative: Change the Pull Request generator to accept a pattern/regex for `repo` attribute, and if left empty it should find all the repos. Using this in conjunction with SCM generator will most likely hit the rate limits within seconds, so it must be very well optimized.

**Comment by fardin01** [comment]
The above alternative is probably a good enhancement to the Pull Request generator in general. But embedding the Pull Request generator into the SCM generator has the added benefit of using the SCM generator's filters and listing pull requests only for the filtered repos.

**Comment by fardin01** [comment]
@jgwest Would love your thoughts before I start working on this :)

**Comment by crenshaw-dev** [comment]
@fardin01 how would you feel about adding templating support to the second generator in a matrix generator? Basically pass each variable set produced by the first generator to the second generator and perform substitution before running the generator.

Something like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp
spec:
  generators:
    - matrix:
        generators:
        - scmProvider:
            github:
              organization: myorg
        - pullRequest:
            github:
              owner: myorg
              repo: "{{repoURL}}"
  template:
   ....
```
