### ISSUE TITLE
Ability to deploy to a different namepace using the ApplicationSet PR Generator

### ISSUE THREAD

**Issue by jgwest** [argoproj/applicationset#467]
The following enhancement request is from @christianh814:

Currently the Generator will deploy an Application to the same namespace, if there is a namespace YAML in the Git repo. [@christianh814] would like to be able to test a PR in it's own namespace.

Example:

Given the following repo: https://github.com/christianh814/gitops-examples

And the following config
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bgd-pr-testing
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        owner: christianh814
        repo: gitops-examples
        labels:
        - preview
      requeueAfterSeconds: 300
  template:
    metadata:
      name: 'bgd-{{branch}}-{{number}}'
    spec:
      source:
        repoURL: 'https://github.com/christianh814/gitops-examples'
        targetRevision: '{{head_sha}}'
        path: bgd/
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      destination:
        server: https://kubernetes.default.svc
        namespace: 'bgd-{{branch}}-{{number}}'
```

This should create this application in a new namespace called bgd-main-1 when a PR is labeled as preview (even though there is a namespace YAML in that directory)
