### ISSUE TITLE
Why are child templates ignored in merge and matrix generators?

### ISSUE THREAD

**Issue by ssomuah** [argoproj/applicationset#482]
Hi, I'm trying to use the merge generators with templates, but the documentation points out that templated in child generators are ignored. I'm curious as to why and whether there's another way to achieve what I want.  

I'm trying to use generators additively because I need to optionally include a field in the spec for the Application. 

```
spec:
  generators:
    - merge:
        mergeKeys:
          - server
        generators:
          - clusters:
              # some other cluster generator that adds values
          - clusters:
              selector:
                matchExpressions: - {key: isDev, operator: In, values:[dev]}
              template:
                spec:
                  source:
                    path: charts/some-chart
                    repoURL: https://somgit.com/some-chart.git
                    targetRevision: develop
          - clusters:
            selector:
              matchExpressions: - {key: isDev, operator: NotIn, values:[dev]}
            template:
              spec:
                source:
                  chart: some-chart
                  repoURL: https://somehelm.com
                  targetRevision: 1.0
```

In this example I need to have path or chart in the final template but never both.

**Comment by crenshaw-dev** [comment]
@ssomuah I thought about this when implementing merge generator and couldn't think of a use case to justify the extra complexity.

Can you achieve what you're trying to do by using two cluster generators instead of three in a merge generator?

```yaml
spec:
  generators:
  - clusters:
      # add values from the old top-level cluster generator here
      selector:
        matchExpressions: 
          - {key: isDev, operator: In, values:[dev]}
      template:
        spec:
          source:
            path: charts/some-chart
            repoURL: https://somgit.com/some-chart.git
            targetRevision: develop
  - clusters:
      # add values from the old top-level cluster generator here
      selector:
        matchExpressions: 
          - {key: isDev, operator: NotIn, values:[dev]}
      template:
        spec:
          source:
            chart: some-chart
            repoURL: https://somehelm.com
            targetRevision: 1.0
```
