### ISSUE TITLE
Application Set not allowing to use jqPathExpressions

### ISSUE THREAD

**Issue by mksha** [argoproj/applicationset#486]
In ApplicationSet, I am not able to use jqPathExpressions under ignoreDifferences. getting validation errors

Argocd Version used: 2.1.1
Application Set version: 0.3.0

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: xxxsds
  namespace: argocd
spec:
  generators:
   ...
  template:
    metadata:
      name: xyzzy
    spec:
      ignoreDifferences:
      - group: networking.istio.io
        kind: VirtualService
        jqPathExpressions:
        - .spec.http[*].route[*].weight
```

```
error validating data: [ValidationError(ApplicationSet.spec.template.spec.ignoreDifferences[0]): unknown field "jqPathExpressions" in io.argoproj.v1alpha1.ApplicationSet.spec.template.spec.ignoreDifferences, ValidationError(ApplicationSet.spec.template.spec.ignoreDifferences[0]): missing required field "jsonPointers" in io.argoproj.v1alpha1.ApplicationSet.spec.template.spec.ignoreDifferences]
```
