### ISSUE TITLE
applicationset，supprt add .spec.generatos.list.iamgeRegistroy args

### ISSUE THREAD

**Issue by zhengyansheng** [argoproj/applicationset#512]
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      - cluster: engineering-dev
        url: https://kubernetes.default.svc
        imageRegistry: xxx-registry.cn-beijing.cr.aliyuncs.com/dev         *************** support args
     - cluster: engineering-prod
       url: https://kubernetesxxx.default.svc
       imageRegistry: ccr.ccs.tencentyun.com/prod                                 *************** support args
  template:
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj-labs/applicationset.git
        targetRevision: HEAD
        path: examples/list-generator/guestbook/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: guestbook
```

For example, I have two k8s clusters, cluster1 and cluster2,

Cluster1 cluster is the of Tencent cloud and uses the image warehouse of Tencent cloud,

Cluster2 cluster is owned by Alibaba cloud and uses Alibaba cloud's image warehouse,

Obviously, the addresses of the two image warehouses are different;

If I want to manage this scenario through Argo applicationset, when I upgrade the deployment image of cluster1, the deployment of cluster2 will also change, but how to achieve this
