### ISSUE TITLE
Pull Request Generator failing with event not defined to be parsed

### ISSUE THREAD

**Issue by runderwoodcr14** [argoproj/applicationset#516]
After I upgrade the applicationset to v0.3.0 on argoCD v2.1.6, I tried to start using the Pull Request generator, however argocd is returning this error:

```
time="2022-02-22T11:44:46Z" level=info msg="Webhook processing failed: event not defined to be parsed"
time="2022-02-22T11:44:47Z" level=info msg="Webhook processing failed: event not defined to be parsed"
time="2022-02-22T11:44:47Z" level=info msg="Webhook processing failed: event not defined to be parsed"
```
Here is my applicationset yaml

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-cleaner-pr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - pullRequest:
      github:
        # The GitHub organization or user.
        owner: org
        # The Github repository
        repo: somerepo
        # Reference to a Secret containing an access token. (optional)
        tokenRef:
          secretName: argocd-secret
          key: webhook.github.secret
        # Labels is used to filter the PRs that you want to target. (optional)
        labels:
          - preview
  requeueAfterSeconds: 300
  template:
    metadata:
      name: "kube-cleaner-{{ branch }}-{{ number }}"
    spec:
      project: infrastructure
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - Validate=true
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: git@github.com:org/somrepo.git
        targetRevision: "{{head_sha}}"
        path: applications/kube-cleaner/overlays/development
        plugin:
          name: argocd-vault-plugin-kustomize
      destination:
        name: development
        namespace: "kube-cleaner-{{ branch }}-{{ number }}"
```

The event from Github:
```
Request URL: https://argocd.example.com/api/webhook
Request method: POST
Accept: */*
content-type: application/json
User-Agent: GitHub-Hookshot/45c393e
X-GitHub-Delivery: 3dd1c430-93d4-11ec-88a0-d62024900628
X-GitHub-Event: pull_request
```

Note that domains, repo names and org has been used as examples instead of real ones
