### ISSUE TITLE
Add the ability to use templating on generators values

### ISSUE THREAD

**Issue by ShauliSolomovich** [argoproj/applicationset#518]
enhancement request.

Today when using variables of generator in the template we can only use them as they are (raw values).
we need the ability to manipulate those values in order to create a valid Application
.
for example, some of our integrations creating automatic branches that we want to create an Application for, but the name of the branch is generated to something like that `my-integration/update-version-x.y.z`. which will fail because the name can't contain those characters ( `\` and `.`)

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
    app: my-app
  name: my-app-pr
spec:
  generators:
  - pullRequest:
      github:
        ...
  template:
    metadata:
      labels:
        app: my-app
      name: my-app-{{branch | replace "/" "-" | replace "." "-" }}
      namespace: default
    spec:
      destination:
        namespace: default
        server: https://kubernetes.default.svc
      project: default

```
