### ISSUE TITLE
Matrix generator where a generator can reference items of another one

### ISSUE THREAD

**Issue by gaeljw** [argoproj/applicationset#530]
I'm wondering if this would be possible that a generator use another's generator items.

For instance, imagine the following manifests structure on a GitOps repository:
```
- dev
    - instanceA
    - instanceB
- prod
    - instanceA
    - instanceB
    - instanceC
    - instanceD
```

Each instance being defined as a single Argo application. Thus 6 instances, 6 Argo applications.

Right now, I use a List generator with 6 items corresponding to the 6 variants.

I would like to be able to define a Matrix generator that would combine:
- a list generator for the 1st level (dev/prod)
- a git directory generator for the 2nd level but here the path should be able to reuse the list generator attribute

Something like (draft):
```yaml
generators:
  - matrix: 
    - list:
        elements:
          - platform: dev
            cluster: dev
          - platform: prod
            cluster: prod
    - git:
       directories:
         - path: {{platform}}/*
```

That's not possible for now, right? Or did I miss something?
