### ISSUE TITLE
Argo CD Image Updater causes an infinite loop of syncs with ApplicationSets

### ISSUE THREAD

**Issue by RiverPhillips** [argoproj/applicationset#547]
**Describe the bug**
I am using ApplicationSets to deploy multiple applications, the template for this ApplicationSet is creating applications with the required annotations for the image updater. This leads to the applications syncing constantly.

I cannot use git writeback with the Argo image updater as I want to ensure the image tagged main is always deployed.

I have raised a bug with the Argo CD Image updater and [they suspect the issue lies with ApplicationSets](https://github.com/argoproj-labs/argocd-image-updater/issues/400#issuecomment-1066647663)

**To Reproduce**
Steps to reproduce the behaviour:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: name
  namespace: argocd
spec:
  generators:
  - git:
      directories:
      - path: manifests/*/overlays/dev
      repoURL: git@github.com:org/repo.git
      revision: HEAD
  template:
    metadata:
      annotations:
        argocd-image-updater.argoproj.io/image-list: app=foo:main
        argocd-image-updater.argoproj.io/app.update-strategy: digest
      name: '{{path[1]}}'
    spec:
      destination:
        namespace: name
        server: https://kubernetes.default.svc/
      project: project
      source:
        path: '{{path}}'
        repoURL: git@github.com:org/repo.git
        targetRevision: HEAD
```

**Expected behaviour**
When the image digest changes there should be a sync, but this should not be an infinite loop.

**Version**
Argo CD: v2.3.1
Argo CD Image Updater: v 0.11.3
