### ISSUE TITLE
[bug] git generator wont add map or list as values

### ISSUE THREAD

**Issue by ofirshtrull** [argoproj/applicationset#552]
Hello to all
I want to have an applicationset for an external chart i.e `kube-prometheus-stack`  each cluster has many different values and I want to manage the values via a clean and per env value file
so I created the next two files
config/prometheus-operator/dev.yaml
```yaml
cluster_name: test-cluster
cluster_url: "https://8.8.8.8/"
cluster_env: "test"

prometheus:
  ofir:
    i_work_to: yeap
```

prometheus-applicationset.yaml
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/xxxx/argocd-config.git
      revision: infra
      files:
      - path: "config/prometheus-operator/*.yaml"
  template:
    metadata:
      labels:
        cluster: "{{cluster_name}}"
      name: "prometheus-stack-{{cluster_name}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        chart: kube-prometheus-stack
        repoURL: https://prometheus-community.github.io/helm-charts
        targetRevision: 33.2.0
        helm:
          values: |
            nameOverride: kube-prometheus-stack
            '{{prometheus}}' # result is a map


      destination:
        server: "{{ cluster_url }}"
        namespace: "monitoring"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
```

the main problem I get is that I cant add values that are set as a map
any workaround? or trick to get them to work?
and just an FYI
`ofir: '{{prometheus.ofir.i_work_to}}'  # result is a string`
work just fine, the problem starts when I try to pass a map

**Comment by elebioda** [comment]
Any thoughts on this bug?

**Comment by zbialik** [comment]
@ofirshtrull idk if it applies to you, but I got the helm values working by passing in the entire values.yaml as a parameter (multi-line string).

So for appset, you might have:
```
spec:
  template:
    spec:
      source:
        helm:
          values: '{{helmValues}}'
```

And the discovered `config.yaml` file via Git File Generator may have contents:
```
cluster_name: test-cluster
cluster_url: "https://8.8.8.8/"
cluster_env: "test"

helmValues: |
  nameOverride: kube-prometheus-stack
  ofir:
    i_work_to: yeap
```

**Comment by barthy1** [comment]
Unfortunately the mentioned workaround doesn't work for me with 2.4.10 . Any other suggestions?

**Comment by manuelchichi** [comment]
We are having this issue in our company. What we want to achieve is to have two different repositories in which one is private and the other is public to a specific client. Then we allow this client to freely edit values in the public one (to only allow changes on image tags). Finally, using the merge generator with two git generators we join both repositories and substitute the values of the tags.The workaround suggested [here](https://github.com/argoproj/applicationset/issues/552#issuecomment-1134913507) (multi line string) unfortunately allows our client to modify any value because the merge can't check the content inside the string. Also we can have different tags in our apps so we can't use parameters or such.

The merge generator creates the following yaml:
```
helmValues:
  nameOverride: kube-prometheus-stack
  ofir:
    i_work_to: yeap
```

In the application set we want to use it like this:
```
helm:
  values: |
    '{{helmValues}}'  #This Doesn't resolve
```

And the desired yaml would something similar to:
```
helm:
  values: |
    nameOverride: kube-prometheus-stack
    ofir:
      i_work_to: yeap
```

**Comment by joshuasimon-taulia** [comment]
i would like to iterate over a yaml list from a git file generator, but i can't get `{{releases}}`, `{{releases[0]}}`, `{{releases.0}}`, etc to render in the below example.
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: abc-values-test
spec:
  generators:
  - git:
      repoURL: https://github.com/abc/def
      revision: HEAD
      files:
      - path: helmfiles/abc/helmfile.yaml
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: abc
      source:
        repoURL: https://github.com/abc/def
        targetRevision: HEAD
        path: '{{path}}'
        plugin:
          env:
          - name: HELM_TEMPLATE_OPTIONS
            value: --skip-tests
          - name: HELMFILE_GLOBAL_OPTIONS
            value: -l name={{releases[0]}} # or however the index is supposed to work
          - name: HELMFILE_USE_CONTEXT_NAMESPACE
            value: "true"
          name: helmfile
      destination:
        server: https://yolo.com
        namespace: '{{path.basename}}'
      ignoreDifferences:
      - group: admissionregistration.k8s.io
        jqPathExpressions:
        - .webhooks[].namespaceSelector.matchExpressions[] | select(.key == "control-plane")
        kind: MutatingWebhookConfiguration
        name: istio-sidecar-injector
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
```

where releases in helmfile.yaml is
```
releases:
- chart: istio/base
  version: 1.12.2
  name: istio-base
  values:
  - jx-values.yaml
  - istio-base-values.yaml
- chart: istio/istiod
  version: 1.12.2
  name: istiod
  values:
  - jx-values.yaml
  - istiod-values.yaml
```

**Comment by joshuasimon-taulia** [comment]
it looks like the [git file generator flattens the contents of maps/arrays](https://github.com/argoproj/applicationset/blob/de10506d8ff81970567381ef3f4dae4b76f50220/pkg/generators/git_test.go#L369-L409)
so basically,
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: abc-values-test
spec:
  generators:
  - git:
      repoURL: https://github.com/abc/def
      revision: HEAD
      files:
      - path: helmfiles/abc/helmfile.yaml
  template:
    metadata:
      name: '{{path.basename}}-{{releases.0.name}}'
```
will work, but it seems like printing the entire `'{{prometheus}}'` map or looping over a list the way i want to is impossible
