### ISSUE TITLE
function "cluster" not defined

### ISSUE THREAD

**Issue by stephaneetje** [argoproj/applicationset#553]
I'm trying to use application set with elements list as follow :

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-ingress
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  generators:
  - list:
      elements:
      - cluster: monitoring
        url: https://xxxx
        namespace: ingress-nginx
      - cluster: reach5-app
        url: https://xxxx
        namespace: ingress-nginx
  template:
    metadata:
      name: '{{cluster}}-nginx'
    spec:
      source:
        repoURL: git@github.com:ReachFive/ciam-helm.git
        targetRevision: HEAD
        path: helm/ingress-nginx
        helm:
          valueFiles:
          - 'secrets://values-{{cluster}}.yaml'
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
```

But argocd gives me this error :
`failed exit status 1: Error: parse error at (applications/templates/ingress-nginx-test.yaml:19): function "cluster" not defined`

Am i doing something wrong ?
I'm using the latest helm chart with argocd 2.3.1 with applicationsetController embedded.
It looks like it isn't being interpreted by the controller maybe ?

**Comment by toamto94** [comment]
Any response to this?

**Comment by toamto94** [comment]
I also fixed it. The problem is that in case you are pointing to a helm chart, the yaml is interpreted first by helm before it is passed to argo. Therefore, Helm tries to apply a "cluster" function which obviously does not exist. The workaround is to escape the curly brackets in the yaml. In my case, using '{{"{{"}}cluster{{"}}"}}' instead of {{cluster}} solved the problem.

**Comment by petr4** [comment]
@toamto94 Thank you! Great workaround! In the same time it works as well with `matrix` generator. Definitely, we need a fix for the bug

**Comment by icicimov** [comment]
@toamto94 thanks for that! What a horrible bug, ended up with this ugliness for the git generator:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: name
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: ...
      revision: HEAD
      files:
      - path: "argocd/cluster-config/test/**/config.json"
  template:
    metadata:
      name: '{{"{{"}}cluster.name{{"}}"}}-add-ons'
    spec:
      project: default
      source:
        helm:
        ...
      destination:
        server: '{{"{{"}}cluster.server{{"}}"}}'
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
```
