### ISSUE TITLE
ApplicationSet bgd-pr-testing contains unrecognized generators: pullRequest

### ISSUE THREAD

**Issue by jizusun** [argoproj/applicationset#573]
Hi Community, 

I'm getting this error message
```
➜  argocd-bgd git:(patch-1) stern applicationset --tail 7
+ argocd-applicationset-controller-665c58494c-q67ps › argocd-applicationset-controller
argocd-applicationset-controller-665c58494c-q67ps argocd-applicationset-controller time="2022-04-09T06:01:08Z" level=info msg="processing event for cluster secret" name=argocd-default-cluster-config namespace=project-hub-research-protal-bp type=createSecretEventHandler
argocd-applicationset-controller-665c58494c-q67ps argocd-applicationset-controller time="2022-04-09T06:01:08Z" level=info msg="listed ApplicationSets" count=1 type=createSecretEventHandler
argocd-applicationset-controller-665c58494c-q67ps argocd-applicationset-controller time="2022-04-09T06:01:08Z" level=warning msg="ApplicationSet bgd-pr-testing contains unrecognized generators: pullRequest"
argocd-applicationset-controller-665c58494c-q67ps argocd-applicationset-controller time="2022-04-09T06:01:08Z" level=info msg="generated 0 applications" generator="{<nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil>}"
argocd-applicationset-controller-665c58494c-q67ps argocd-applicationset-controller time="2022-04-09T06:01:08Z" level=debug msg="apps from generator: []" generator="{<nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil>}"
argocd-applicationset-controller-665c58494c-q67ps argocd-applicationset-controller time="2022-04-09T06:01:08Z" level=info msg="end reconcile" requeueAfter=0s
argocd-applicationset-controller-665c58494c-q67ps argocd-applicationset-controller time="2022-04-09T06:11:07Z" level=info msg="Alloc=8746 TotalAlloc=30677 Sys=32466 NumGC=12 Goroutines=79"
```

And I installed my ArgoCD with ArgoCD Operator, and both `ArgoCD` and `ApplicationSetController` are the the latest version
```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
spec:
  version: v2.3.3
  usersAnonymousEnabled: true
  statusBadgeEnabled: true
  applicationSet: 
    version: v0.4.1
    logLevel: debug
  server:
    insecure: true
    autoscale:
      enabled: false
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    resources:
      limits:
        cpu: 50m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 128Mi
    route:
      enabled: true
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
    service:
      type: ''
  grafana:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  prometheus:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  initialSSHKnownHosts: {}
  rbac: {}
  repo:
    execTimeout: 360
    resources:
      limits:
        cpu: 50m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 128Mi
  dex:
    resources:
      limits:
        cpu: 50m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 128Mi
  ha:
    enabled: false
    resources:
      limits:
        cpu: 50m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 128Mi
  tls:
    ca: {}
  redis:
    resources:
      limits:
        cpu: 50m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 128Mi
  controller:
    processors: {}
    resources:
      limits:
        cpu: 100m
        memory: 512Mi 
      requests:
        cpu: 50m
        memory: 256Mi
    sharding: {}
```

What can I do fix the problem?

Best regards,
Jizu
