### ISSUE TITLE
Cluster Resource Generator

### ISSUE THREAD

**Issue by aslafy-z** [argoproj/applicationset#600]
Add the ability to generate Applications from downstream cluster resources, eg:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-addon
  namespace: argocd
spec:
  generators:
    - clusterResource:
        apiVersion: tenant.io/v1
        kind: Tenant
        # namespace: <optional>
        labelSelector:
          matchLabels:
            tenant.io/sync: 'true'
```

```yaml
apiVersion: tenant.io/v1
kind: Tenant
metadata:
  name: tenant1
  labels:
    tenant.io/sync: 'true'
spec: {}
```

```yaml
apiVersion: tenant.io/v1
kind: Tenant
metadata:
  name: tenant2
  labels:
    tenant.io/sync: 'true'
spec: {}
```

ArgoCD should generate two applications from these resources.
