### ISSUE TITLE
scmProvider Github filter combination (repositoryMatch + labelMatch) not generating apps

### ISSUE THREAD

**Issue by dllegru** [argoproj/applicationset#605]
We have a repository with a label created.

We are using `scmProvider` with filters `repositoryMatch` + `labelMatch`, 0 applications are being generated.

Reading the [Filters documentation](https://argocd-applicationset.readthedocs.io/en/stable/Generators-SCM-Provider/#filters) I understand this combination should be possible.

- scmProvider used 
```
    - scmProvider:
        github:
          # The GitHub organization to scan.
          organization: my-org
          # If true, scan every branch of every repository. If false, scan only the default branch. Defaults to false.
          allBranches: true
        filters:
          - repositoryMatch: platform-daniel-tests
            labelMatch: deploy
```
(setting `allBranches` to false doesn't make any difference)

- curl to github showing the label exists
```
❯   curl \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <auth>" \
  https://api.github.com/repos/my-org/platform-daniel-tests/labels
[
...
  {
    "id": xxxx,
    "node_id": "xxxx",
    "url": "https://api.github.com/repos/my-org/platform-daniel-tests/labels/deploy",
    "name": "deploy",
    "color": "B29356",
    "default": false,
    "description": ""
  },
...
]
```

- applicationSet logs showing 0 applications generated
```
{"generator":{"scmProvider":{"github":{"organization":"my-org","tokenRef":{"secretName":"temp-dev-daniel-github-token","key":"token"},"allBranches":true},"filters":[{"repositoryMatch":"platform-daniel-tests","labelMatch":"deploy"}],"cloneProtocol":"https","template":{"metadata":{},"spec":{"source":{"repoURL":""},"destination":{},"project":""}}}},"level":"info","msg":"generated 0 applications","time":"2022-10-04T11:32:27Z"}
```
