### ISSUE TITLE
Merge generator where a generator can reference items of another one

### ISSUE THREAD

**Issue by jpcosal** [argoproj/applicationset#606]
Very much like what's been added for the Matrix generator [here](https://github.com/argoproj/argo-cd/pull/9080), it would be nice to have the same for the Merge generator.
Something like
```
  generators:
    - merge:
        mergeKeys:
          - name
        generators:
          - git:
              repoURL: https://github.com/my_org/my_repo.git
              revision: my_revision
              files:
                - path: path/*.yaml
          - git:
              repoURL: https://github.com/my_org/my_repo2.git
              revision: '{{sha}}'
              files:
                - path: path2/**/file.yaml
```
Notice the `{{sha}}` reference in the second generator.

cf original issue for merge generator [here](https://github.com/argoproj/applicationset/issues/530)

This is currently not possible, if I'm not mistaken?

I'd gladly create a PR for that.
