### ISSUE TITLE
FATA[0000] rpc error: code = Unimplemented desc = unknown service applicationset.ApplicationSetService

### ISSUE THREAD

**Issue by renperez-cpi** [argoproj/applicationset#608]
i am trying to use the latest argocd cli with appset to apply this applicationset but getting error when applying by running this command argocd appset create file.yaml
```
FATA[0000] rpc error: code = Unimplemented desc = unknown service applicationset.ApplicationSetService
```
here is the sample application set.
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: deploy-teleport-configmap
spec:
  generators:
  - list:
      elements:
      - prefix: teleport-configmap-us-west-2
        url: eks-cluster-1
        region: us-west-2
        environment: qa
      - prefix: teleport-configmap-eu-central-1
        url: eks-cluster-2
        region: eu-central-1
        environment: qa
      - prefix: teleport-configmap-ca-central-1
        url: eks-cluster-3
        region: ca-central-1
        environment: qa
  template:
    metadata:
      name: '{{prefix}}'
    spec:
      project: teleport
      source:
        repoURL: url-repo
        targetRevision: initial-testing
        path: deploy/argocd/config/teleport/{{region}}
      destination:
        server: '{{url}}'
        namespace: teleport
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
```
