### ISSUE TITLE
ApplicationSet not able to render helm chart when value is not defined in generator list

### ISSUE THREAD

**Issue by simonstumpf** [argoproj/applicationset#619]
Hi All,

We're using ApplicationSets heavily in our setup. 
In our Helm Chart we define all values in the values.yaml file, which in some cases need to be overwritten. 
In that case we add a value to the generators list elements. 

However I can't just use this in one of the elements array. 
For example if I need to change the cpu requests, I have to define the cpu requests value in all elements of the generators list. 

It would be quiet handy if ArgoCD was able to check if there is a default value configured instead of throwing an error:
`failed exit status 1: Error: failed parsing --set data: key "}" has no value`

Here is an example, maybe this helps you
```
spec:
  generators:
    - list:
        elements:
          - stage: prd
            cpuRequests: 500mi
          - stage: dev
           # no cpuRequests defined, here the default value defined in the values.yaml file of the Chart should be used

```
