### ISSUE TITLE
Application Set with Existing Project Issue

### ISSUE THREAD

**Issue by sabinayakc** [argoproj/applicationset#643]
I create a project with

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
   name: my-proj
   namespace: argocd
spec:
   clusterResourceWhitelist:
   - group: '*'
     kind: '*'
   namespaceResourceWhitelist:
   - group: '*'
     kind: '*'
   description: "My Desc"
   destinations:
   - name: my-cluster
     namespace: '*'
     server: '*'
   sourceRepos:
   - https://github.com/example/myrepo.git
```

And then I create a argocd application set via, `argocd appset create -f my-appset.yaml`

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-appset
  namespace: argocd
spec:  
  generators:
  - git:
      repoURL: https://github.com/example/myrepo.git
      revision: HEAD
      directories:
      - path: src/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: my-proj # ---> This is from above.
      source:
        repoURL: https://github.com/example/myrepo.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        name: my-cluster
        namespace: '{{path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
 ```
 
 But, when I apply the appset, it overwrites the project and removes the destinations, scoped repos, whitelist etc.
 
 I also tried removing the project, and letting appset create the project but I dont know how to supply the scoped repos and other settings.
 
 Anyone had any luck?
